# Generated by Django 5.2.1 on 2025-06-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PageInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='content_pillar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
